# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-22.04  # Specify Ubuntu 22.04 LTS
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.4  # Use the Go version you need
        
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Replace with your deployment script or commands here
          cd /var/www/api-duren/html
          sudo git pull origin main
          sudo go mod vendor
          sudo go build .
          sudo service goweb restart  # Restart your application
